module.exports = {
  admin: [
  "admin_id", 
  "type",
  "fname",
  "lname",
  "email",
  "password",
  "photo",
  "gender",
  "passwordChangedAt",
  "passwordResetToken",
  "passwordResetExpires",
],
  surfer: [
    "id",
    "fname",
    "lname",
    "email",
    "password",
    "photo",
    "gender",
    "birth_date",
    "closed_admin",
    "last_login",
    "is_active",
    "created_date",
    "passwordChangedAt",
    "passwordResetToken",
    "passwordResetExpires",
    "address",
    "jop",
    "education",
    "interests",
    "cover_photo"
  ],
  marketer: [
    "id",
    "fname",
    "lname",
    "email",
    "password",
    "photo",
    "closed_admin",
    "is_active",
    "last_published",
    "founded_at",
    "passwordChangedAt",
    "passwordResetToken",
    "passwordResetExpires",
    "cover_photo"
  ],
  post: [
    "id",
    "post_text",
    "surfer_id",
    "has_multimedia",
    "created_date",
    "comment_counter",
  ],
  comment: [
    "id",
    "post_id",
    "comment_user_id",
    "comment_content",
    "comment_time",
  ],
  favpost: ["post_id", "surfer_id"],
  friend: ["source_id", "target_id", "friendship_time", "blocked"],
  like: ["type", "post_id", "surfer_id", "like_time"],
  share: ["post_id", "surfer_id", "share_time"],
  location: ["id", "surfer_id", "description", "maplink", "created_date"],
  mar_reports_mar: ["reported_id", "reporter_id", "report_option"],
  post_media: ["link", "post_id", "type"],
  product: [
    "id",
    "marketer_id",
    "product_text",
    "avg_rating",
    "price",
    "created_date",
    "reviews_counter",
    "product_name",
  ],
  product_media: ["link", "product_id", "type"],
  review: [
    "id",
    "surfer_id",
    "product_id",
    "rating",
    "rating_time",
    "rating_content",
  ],
  sur_rep_mar: ["sur_id", "mar_id", "report_option"],
  sur_rep_post: ["sur_id", "post_id", "report_option"],
  sur_rep_pro: ["sur_id", "pro_id", "report_option"],
  sur_rep_sur: ["reporter_id", "reported_id", "report_option"],
};
